name: Bundle NPM App CI

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  bundle-app-npm-ci:
    uses: Forsakringskassan/.github/.github/workflows/bundle-app-npm-ci.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
